import { factory } from 'treason-di';
import { Browser } from 'puppeteer';
import eveClientFactory from './Factory/eveClientFactory';
import slashCommandArrayFactory from './Factory/slashCommandArrayFactory';
import EveClient from './Structures/EveClient';
import connectionFactory from './Factory/connectionFactory';
import playlistCommandArrayFactory from './Factory/playlistCommandArrayFactory';
import browserFactory from './Factory/browserFactory';
import PlaylistCommand from './SlashCommands/Music/Playlist/PlaylistCommand';
import playlistCommandFactory from './SlashCommands/Music/Playlist/Factory/playlistCommandFactory';
import PlaylistDeleteCommand from './SlashCommands/Music/Playlist/PlaylistDeleteCommand';
import playlistDeleteCommandFactory from './SlashCommands/Music/Playlist/Factory/playlistDeleteCommandFactory';
import PlaylistListCommand from './SlashCommands/Music/Playlist/PlaylistListCommand';
import playlistListCommandFactory from './SlashCommands/Music/Playlist/Factory/playlistListCommandFactory';
import PlaylistLoadCommand from './SlashCommands/Music/Playlist/PlaylistLoadCommand';
import playlistLoadCommandFactory from './SlashCommands/Music/Playlist/Factory/playlistLoadCommandFactory';
import PlaylistSaveCommand from './SlashCommands/Music/Playlist/PlaylistSaveCommand';
import playlistSaveCommandFactory from './SlashCommands/Music/Playlist/Factory/playlistSaveCommandFactory';
import buttonInteractionArrayFactory from './Factory/buttonInteractionArrayFactory';
import { EventStore } from './eventStore/EventStore';
import eventStoreFactory from './eventStore/Factory/EventStoreFactory';
import BanInteraction from './ButtonInteractions/BanInteraction';
import banInteractionFactory from './ButtonInteractions/Factory/banInteractionFactory';
import KickInteraction from './ButtonInteractions/KickInteraction';
import MenuInteraction from './ButtonInteractions/MenuInteraction';
import PardonInteraction from './ButtonInteractions/PardonInteraction';
import kickInteractionFactory from './ButtonInteractions/Factory/kickInteractionFactory';
import menuInteractionFactory from './ButtonInteractions/Factory/menuInteractionFactory';
import pardonInteractionFactory from './ButtonInteractions/Factory/pardonInteractionFactory';
import BanCommand from './SlashCommands/BanCommand';
import KickCommand from './SlashCommands/KickCommand';
import PardonCommand from './SlashCommands/PardonCommand';
import banCommandFactory from './SlashCommands/Factory/banCommandFactory';
import kickCommandFactory from './SlashCommands/Factory/kickCommandFactory';
import pardonCommandFactory from './SlashCommands/Factory/pardonCommandFactory';
import PlaylistProjection from './Projection/PlaylistProjection';
import playlistProjectionFactory from './Projection/Factory/playlistProjectionFactory';
import PlayCommand from './SlashCommands/Music/PlayCommand';
import playCommandFactory from './SlashCommands/Music/Factory/PlayCommandFactory';
import spotifyApiFactory from './Factory/spotifyApiFactory';
import YtResultService from './MusicPlayer/YtResultService';
import YtResultServiceFactory from './MusicPlayer/Factory/ytResultServiceFactory';

const definitions = new Map();
definitions.set(Browser, factory(browserFactory));
definitions.set(EveClient, factory(eveClientFactory));
definitions.set(EventStore, factory(eventStoreFactory));
definitions.set(PlaylistProjection, factory(playlistProjectionFactory));
definitions.set(YtResultService, factory(YtResultServiceFactory));
definitions.set('SpotifyApi', factory(spotifyApiFactory));
definitions.set('ButtonInteraction', factory(buttonInteractionArrayFactory));
definitions.set('SlashCommands', factory(slashCommandArrayFactory));
definitions.set('PlaylistCommands', factory(playlistCommandArrayFactory));
definitions.set('Connection', factory(connectionFactory));

definitions.set(PlaylistCommand, factory(playlistCommandFactory));
definitions.set(PlaylistDeleteCommand, factory(playlistDeleteCommandFactory));
definitions.set(PlaylistListCommand, factory(playlistListCommandFactory));
definitions.set(PlaylistLoadCommand, factory(playlistLoadCommandFactory));
definitions.set(PlaylistSaveCommand, factory(playlistSaveCommandFactory));
definitions.set(PlayCommand, factory(playCommandFactory));

definitions.set(BanInteraction, factory(banInteractionFactory));
definitions.set(KickInteraction, factory(kickInteractionFactory));
definitions.set(MenuInteraction, factory(menuInteractionFactory));
definitions.set(PardonInteraction, factory(pardonInteractionFactory));

definitions.set(BanCommand, factory(banCommandFactory));
definitions.set(KickCommand, factory(kickCommandFactory));
definitions.set(PardonCommand, factory(pardonCommandFactory));

export default definitions;
